In [2]:
import numpy as np

In [3]:
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)


1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Array properties
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Dimensions:", arr2.ndim)

# Indexing
print("First element:", arr1[0])
print("Last element:", arr1[-1])

# Slicing
print("Sliced array:", arr1[1:4])

# Arithmetic operations
print("Addition:", arr1 + 5)
print("Multiplication:", arr1 * 2)

# Reshaping
arr3 = np.arange(1, 7)
print("Original array:", arr3)
print("Reshaped array:\n", arr3.reshape(2, 3))

# Zeros and ones
print("Zeros:", np.zeros(5))
print("Ones:", np.ones(5))

Shape: (2, 3)
Size: 6
Dimensions: 2
First element: 10
Last element: 50
Sliced array: [20 30 40]
Addition: [15 25 35 45 55]
Multiplication: [ 20  40  60  80 100]
Original array: [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
